/*
 Navicat Premium Data Transfer

 Source Server         : idata-mysql-test
 Source Server Type    : MySQL
 Source Server Version : 50734
 Source Host           : idata-ptag-mysql-master-fh-t.seeke.net:3306
 Source Schema         : ptag

 Target Server Type    : MySQL
 Target Server Version : 50734
 File Encoding         : 65001

 Date: 20/04/2024 15:17:51
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for t_attribute_location_vip
-- ----------------------------
DROP TABLE IF EXISTS `t_attribute_location_vip`;
CREATE TABLE `t_attribute_location_vip`  (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `template_code` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '模板code',
  `sql_location` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'sql位置',
  `attribute_id` int(11) NULL DEFAULT NULL COMMENT '属性id',
  `gp_column_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'gp列名',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 427 CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = '属性模板内位置' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of t_attribute_location_vip
-- ----------------------------
INSERT INTO `t_attribute_location_vip` VALUES (2, 'parseNotDoTemplate', 'where_1', 2, 'dt');
INSERT INTO `t_attribute_location_vip` VALUES (3, 'parseNotDoTemplate', 'where_2', 6, 'is_rgst');
INSERT INTO `t_attribute_location_vip` VALUES (4, 'parseNotDoTemplate', 'where_2', 7, 'pv_qty');
INSERT INTO `t_attribute_location_vip` VALUES (5, 'parseNotDoTemplate', 'where_2', 8, 'spt_qty');
INSERT INTO `t_attribute_location_vip` VALUES (6, 'parseNotDoTemplate', 'where_2', 9, 'clt_egds_qty');
INSERT INTO `t_attribute_location_vip` VALUES (7, 'parseNotDoTemplate', 'where_2', 10, 'pay_ord_qty');
INSERT INTO `t_attribute_location_vip` VALUES (8, 'parseNotDoTemplate', 'where_3|on_1', 1, 'prmry_busi_mdl_cd');
INSERT INTO `t_attribute_location_vip` VALUES (10, 'parseDoTemplate', 'selectsum_1|where_2', 13, 'pv_qty');
INSERT INTO `t_attribute_location_vip` VALUES (11, 'parseDoTemplate', 'selectsum_1|where_2', 14, 'pv_day_qty');
INSERT INTO `t_attribute_location_vip` VALUES (12, 'parseDoTemplate', 'selectsum_1|where_2', 15, 'spt_qty');
INSERT INTO `t_attribute_location_vip` VALUES (13, 'parseDoTemplate', 'selectsum_1|where_2', 16, 'spt_egds_qty');
INSERT INTO `t_attribute_location_vip` VALUES (14, 'parseDoTemplate', 'selectsum_1|where_2', 17, 'clt_egds_qty');
INSERT INTO `t_attribute_location_vip` VALUES (15, 'parseDoTemplate', 'selectsum_1|where_2', 18, 'pay_ord_qty');
INSERT INTO `t_attribute_location_vip` VALUES (16, 'parseDoTemplate', 'selectsum_1|where_2', 19, 'pay_egds_qty');
INSERT INTO `t_attribute_location_vip` VALUES (17, 'parseDoTemplate', 'selectsum_1|where_2', 20, 'pay_ord_amt');
INSERT INTO `t_attribute_location_vip` VALUES (18, 'parseDoTemplate', 'selectsum_1|where_2', 21, 'pay_ord_amt/pay_ord_qty');
INSERT INTO `t_attribute_location_vip` VALUES (19, 'parseDoTemplate', 'selectsum_1|where_2', 22, 'pd_pv_qty');
INSERT INTO `t_attribute_location_vip` VALUES (20, 'parseDoTemplate', 'where_1', 1, 'prmry_busi_mdl_cd');
INSERT INTO `t_attribute_location_vip` VALUES (21, 'parseDoTemplate', 'where_1', 2, 'dt');
INSERT INTO `t_attribute_location_vip` VALUES (22, 'parseDoTemplate', 'selectsum_1|where_2', 6, 'is_rgst');
INSERT INTO `t_attribute_location_vip` VALUES (23, 'parseDoTemplate', 'selectsum_1|where_2', 7, 'pv_qty');
INSERT INTO `t_attribute_location_vip` VALUES (24, 'parseDoTemplate', 'selectsum_1|where_2', 8, 'spt_qty');
INSERT INTO `t_attribute_location_vip` VALUES (25, 'parseDoTemplate', 'selectsum_1|where_2', 9, 'clt_egds_qty');
INSERT INTO `t_attribute_location_vip` VALUES (26, 'parseDoTemplate', 'selectsum_1|where_2', 10, 'pay_ord_qty');
INSERT INTO `t_attribute_location_vip` VALUES (27, 'parseDoTemplate', 'selectsum_1|where_2', 11, 'pd_pv_qty');
INSERT INTO `t_attribute_location_vip` VALUES (33, 'parseDoAndTemplate', 'select_1|where_1|group_1|having_1|select_2', 31, 'erp_gds_cd');
INSERT INTO `t_attribute_location_vip` VALUES (34, 'parseDoAndTemplate', 'select_1|where_1|group_1|having_1|select_2', 32, 'erp_brand_id');
INSERT INTO `t_attribute_location_vip` VALUES (35, 'parseDoAndTemplate', 'select_1|where_1|group_1|having_1|select_2', 33, 'dpa_cyc');
INSERT INTO `t_attribute_location_vip` VALUES (36, 'parseDoAndTemplate', 'selectsum_1|where_2', 13, 'pv_qty');
INSERT INTO `t_attribute_location_vip` VALUES (37, 'parseDoAndTemplate', 'selectsum_1|where_2', 14, 'pv_day_qty');
INSERT INTO `t_attribute_location_vip` VALUES (38, 'parseDoAndTemplate', 'selectsum_1|where_2', 15, 'spt_qty');
INSERT INTO `t_attribute_location_vip` VALUES (39, 'parseDoAndTemplate', 'selectsum_1|where_2', 16, 'spt_egds_qty');
INSERT INTO `t_attribute_location_vip` VALUES (40, 'parseDoAndTemplate', 'selectsum_1|where_2', 17, 'clt_egds_qty');
INSERT INTO `t_attribute_location_vip` VALUES (41, 'parseDoAndTemplate', 'rborcardinality_1|where_2', 18, 'erp_order_code_rbm');
INSERT INTO `t_attribute_location_vip` VALUES (42, 'parseDoAndTemplate', 'selectsum_1|where_2', 19, 'pay_egds_qty');
INSERT INTO `t_attribute_location_vip` VALUES (43, 'parseDoAndTemplate', 'selectsum_1|where_2', 20, 'pay_ord_amt');
INSERT INTO `t_attribute_location_vip` VALUES (44, 'parseDoAndTemplate', 'selectsum_1|where_2', 21, 'pay_ord_amt/erp_order_code_rbm');
INSERT INTO `t_attribute_location_vip` VALUES (45, 'parseDoAndTemplate', 'selectsum_1|where_2', 22, 'pd_pv_qty');
INSERT INTO `t_attribute_location_vip` VALUES (46, 'parseDoAndTemplate', 'where_1', 1, 'prmry_busi_mdl_cd');
INSERT INTO `t_attribute_location_vip` VALUES (47, 'parseDoAndTemplate', 'where_1', 2, 'dt');
INSERT INTO `t_attribute_location_vip` VALUES (48, 'parseDoAndTemplate', 'select_1|where_1|group_1|having_1|select_2', 113, 'erp_gds_cd');
INSERT INTO `t_attribute_location_vip` VALUES (49, 'parseDoAndTemplate', 'select_1|where_1|group_1|having_1|select_2', 114, 'erp_gds_cd');
INSERT INTO `t_attribute_location_vip` VALUES (50, 'parseDoAndTemplate', 'select_1|where_1|group_1|having_1|select_2', 116, 'erp_brand_id');
INSERT INTO `t_attribute_location_vip` VALUES (51, 'parseDoAndTemplate', 'select_1|where_1|group_1|having_1|select_2', 117, 'erp_brand_id');
INSERT INTO `t_attribute_location_vip` VALUES (77, 'parseDoAndTemplate', 'where_1', 34, 'dpa_cyc');
INSERT INTO `t_attribute_location_vip` VALUES (78, 'parseDoAndTemplate', 'where_1', 35, 'dpa_cyc');
INSERT INTO `t_attribute_location_vip` VALUES (79, 'parseDoAndTemplate', 'where_1', 36, 'dpa_cyc');
INSERT INTO `t_attribute_location_vip` VALUES (80, 'parseDoAndTemplate', 'where_1', 37, 'dpa_cyc');
INSERT INTO `t_attribute_location_vip` VALUES (81, 'parseDoAndTemplate', 'where_1', 38, 'dpa_cyc');
INSERT INTO `t_attribute_location_vip` VALUES (82, 'parseDoAndTemplate', 'where_1', 39, 'dpa_cyc');
INSERT INTO `t_attribute_location_vip` VALUES (83, 'parseDoAndTemplate', 'where_1', 40, 'dpa_cyc');
INSERT INTO `t_attribute_location_vip` VALUES (84, 'parseDoAndTemplate', 'where_1', 47, 'dpa_cyc');
INSERT INTO `t_attribute_location_vip` VALUES (85, 'parseDoAndTemplate', 'where_1', 49, 'is_color');
INSERT INTO `t_attribute_location_vip` VALUES (86, 'parseDoAndTemplate', 'where_1', 50, 'is_color');
INSERT INTO `t_attribute_location_vip` VALUES (87, 'parseSysUserTemplate', 'where_1', 88, 'is_add_wecom_first_time');
INSERT INTO `t_attribute_location_vip` VALUES (91, 'parseEventDoAndTemplate', 'select_1|where_3|group_1|having_1|select_2', 147, 'erp_gds_cd');
INSERT INTO `t_attribute_location_vip` VALUES (92, 'parseEventDoAndTemplate', 'select_1|where_3|group_1|having_1|select_2', 148, 'erp_brand_id');
INSERT INTO `t_attribute_location_vip` VALUES (93, 'parseEventDoAndTemplate', 'select_1|where_3|group_1|having_1|select_2', 150, 'dpa_cyc');
INSERT INTO `t_attribute_location_vip` VALUES (94, 'parseEventDoAndTemplate', 'select_1|where_3|group_1|having_1|select_2', 152, 'scnd_cate_id');
INSERT INTO `t_attribute_location_vip` VALUES (95, 'parseEventDoAndTemplate', 'selectsum_1|where_2', 130, 'pv_qty');
INSERT INTO `t_attribute_location_vip` VALUES (96, 'parseEventDoAndTemplate', 'selectsum_1|where_2', 131, 'pv_day_qty');
INSERT INTO `t_attribute_location_vip` VALUES (97, 'parseEventDoAndTemplate', 'selectsum_1|where_2', 132, 'spt_qty');
INSERT INTO `t_attribute_location_vip` VALUES (98, 'parseEventDoAndTemplate', 'selectsum_1|where_2', 133, 'spt_egds_qty');
INSERT INTO `t_attribute_location_vip` VALUES (99, 'parseEventDoAndTemplate', 'selectsum_1|where_2', 134, 'clt_egds_qty');
INSERT INTO `t_attribute_location_vip` VALUES (100, 'parseEventDoAndTemplate', 'rborcardinality_1|where_2', 135, 'erp_order_code_rbm');
INSERT INTO `t_attribute_location_vip` VALUES (101, 'parseEventDoAndTemplate', 'selectsum_1|where_2', 136, 'pay_egds_qty');
INSERT INTO `t_attribute_location_vip` VALUES (102, 'parseEventDoAndTemplate', 'selectsum_1|where_2', 137, 'pay_ord_amt');
INSERT INTO `t_attribute_location_vip` VALUES (103, 'parseEventDoAndTemplate', 'selectsum_1|where_2', 138, 'pay_ord_amt/erp_order_code_rbm');
INSERT INTO `t_attribute_location_vip` VALUES (104, 'parseEventDoAndTemplate', 'selectsum_1|where_2', 139, 'pd_pv_qty');
INSERT INTO `t_attribute_location_vip` VALUES (105, 'parseEventDoAndTemplate', 'where_1', 118, 'prmry_busi_mdl_cd');
INSERT INTO `t_attribute_location_vip` VALUES (106, 'parseEventDoAndTemplate', 'where_1', 119, 'dt');
INSERT INTO `t_attribute_location_vip` VALUES (107, 'parseEventDoAndTemplate', 'select_1|where_3|group_1|having_1|select_2', 156, 'erp_gds_cd');
INSERT INTO `t_attribute_location_vip` VALUES (108, 'parseEventDoAndTemplate', 'select_1|where_3|group_1|having_1|select_2', 157, 'erp_gds_cd');
INSERT INTO `t_attribute_location_vip` VALUES (109, 'parseEventDoAndTemplate', 'select_1|where_3|group_1|having_1|select_2', 158, 'erp_brand_id');
INSERT INTO `t_attribute_location_vip` VALUES (110, 'parseEventDoAndTemplate', 'select_1|where_3|group_1|having_1|select_2', 159, 'erp_brand_id');
INSERT INTO `t_attribute_location_vip` VALUES (122, 'parseSysUserTemplate', 'where_1', 447, 'fisrt_pay_time');
INSERT INTO `t_attribute_location_vip` VALUES (123, 'parseSysUserTemplate', 'where_1', 448, 'last_pay_time');
INSERT INTO `t_attribute_location_vip` VALUES (125, 'parseSysUserTemplate', 'where_1', 449, 'last_pv_time');
INSERT INTO `t_attribute_location_vip` VALUES (126, 'parseSysUserTemplate', 'where_1', 99, 'fans_register_time');
INSERT INTO `t_attribute_location_vip` VALUES (127, 'parseSysUserTemplate', 'where_1', 112, 'is_add_wecom_first_time');
INSERT INTO `t_attribute_location_vip` VALUES (128, 'parseDoTemplate', 'where_1', 450, 'fisrt_pay_time');
INSERT INTO `t_attribute_location_vip` VALUES (129, 'parseDoTemplate', 'where_1', 451, 'last_pay_time');
INSERT INTO `t_attribute_location_vip` VALUES (132, 'parseNotDoTemplate', 'where_1', 1000, 'prmry_busi_mdl_cd');
INSERT INTO `t_attribute_location_vip` VALUES (133, 'parseNotDoTemplate', 'where_1', 1001, 'chnl_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (134, 'parseDoTemplate', 'where_1', 1000, 'prmry_busi_mdl_cd');
INSERT INTO `t_attribute_location_vip` VALUES (135, 'parseDoTemplate', 'where_1', 1001, 'chnl_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (136, 'parseDoAndTemplate', 'where_1', 1000, 'prmry_busi_mdl_cd');
INSERT INTO `t_attribute_location_vip` VALUES (137, 'parseDoAndTemplate', 'where_1', 1001, 'chnl_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (138, 'parseSysUserTemplate', 'where_1', 1000, 'prmry_busi_mdl_cd');
INSERT INTO `t_attribute_location_vip` VALUES (139, 'parseSysUserTemplate', 'where_1', 1001, 'chnl_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (140, 'parseEventDoAndTemplate', 'where_1', 1000, 'prmry_busi_mdl_cd');
INSERT INTO `t_attribute_location_vip` VALUES (141, 'parseEventDoAndTemplate', 'where_1', 1001, 'chnl_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (142, 'parseDoAndTemplate', 'where_1', 450, 'fisrt_pay_time');
INSERT INTO `t_attribute_location_vip` VALUES (143, 'parseDoAndTemplate', 'where_1', 451, 'last_pay_time');
INSERT INTO `t_attribute_location_vip` VALUES (144, 'parseEventDoAndTemplate', 'where_1', 452, 'fisrt_pay_time');
INSERT INTO `t_attribute_location_vip` VALUES (145, 'parseEventDoAndTemplate', 'where_1', 453, 'last_pay_time');
INSERT INTO `t_attribute_location_vip` VALUES (152, 'parseDoAndTemplate', 'where_1', 1049, 'scnd_cate_id');
INSERT INTO `t_attribute_location_vip` VALUES (153, 'parseDoAndTemplate', 'where_1', 1050, 'scnd_cate_id');
INSERT INTO `t_attribute_location_vip` VALUES (154, 'parseDoAndTemplate', 'where_1', 1051, 'scnd_cate_id');
INSERT INTO `t_attribute_location_vip` VALUES (155, 'parseDoAndTemplate', 'where_1', 1052, 'scnd_cate_id');
INSERT INTO `t_attribute_location_vip` VALUES (156, 'parseNotDoTemplate', 'where_2', 11, 'pd_pv_qty');
INSERT INTO `t_attribute_location_vip` VALUES (157, 'parseEventDoAndTemplate', 'select_1|where_3|group_1|having_1|select_2', 1056, 'erp_brand_id');
INSERT INTO `t_attribute_location_vip` VALUES (158, 'parseDoAndTemplate', 'select_1|where_1|group_1|having_1|select_2', 1054, 'erp_brand_id');
INSERT INTO `t_attribute_location_vip` VALUES (160, 'parseNotDoPayTemplate', 'where_1', 2, 'dt');
INSERT INTO `t_attribute_location_vip` VALUES (166, 'parseNotDoPayTemplate', 'where_3|on_1|where_1|where_4', 1, 'prmry_busi_mdl_cd');
INSERT INTO `t_attribute_location_vip` VALUES (167, 'parseNotDoPayTemplate', 'where_1', 1000, 'prmry_busi_mdl_cd');
INSERT INTO `t_attribute_location_vip` VALUES (168, 'parseNotDoPayTemplate', 'where_1', 1001, 'chnl_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (170, 'parseAggMaxSceneTemplate', 'select_1|select_2|selectsum_1|order_1|group_1|where_2|wherenotnull_1', 1062, 'cmn_cnee_city_180');
INSERT INTO `t_attribute_location_vip` VALUES (171, 'parseAggMaxSceneTemplate', 'where_1', 1000, 'prmry_busi_mdl_cd');
INSERT INTO `t_attribute_location_vip` VALUES (172, 'parseAggMaxSceneTemplate', 'where_1', 1001, 'chnl_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (173, 'parseSysUserTemplate', 'where_1', 1064, 'rgst_time');
INSERT INTO `t_attribute_location_vip` VALUES (174, 'parseSysUserTemplate', 'havingsum_1', 1065, 'order_qty');
INSERT INTO `t_attribute_location_vip` VALUES (175, 'parseSysUserTemplate', 'arrayorwhere_1', 1067, 'cnee_city_all');
INSERT INTO `t_attribute_location_vip` VALUES (176, 'parseAggMaxSceneTemplate', 'select_1|select_2|selectsum_1|order_1|group_1|where_2|wherenotnull_1', 1066, 'cmn_cnee_city');
INSERT INTO `t_attribute_location_vip` VALUES (177, 'parseSysUserTemplate', 'where_1', 1074, 'fc_date');
INSERT INTO `t_attribute_location_vip` VALUES (178, 'parseSysUserTemplate', 'where_1', 1076, 'fc_date');
INSERT INTO `t_attribute_location_vip` VALUES (179, 'parseSysUserTemplate', 'where_1', 1081, 'fc_date');
INSERT INTO `t_attribute_location_vip` VALUES (180, 'parseSysUserTemplate', 'where_1', 1068, 'erp_cate_id');
INSERT INTO `t_attribute_location_vip` VALUES (184, 'parseSysUserTemplate', 'where_1', 1094, 'is_add_wecom_first_time');
INSERT INTO `t_attribute_location_vip` VALUES (185, 'parseSysUserTemplate', 'where_1', 1096, 'is_add_wecom_first_time');
INSERT INTO `t_attribute_location_vip` VALUES (186, 'parseSysUserTemplate', 'where_1', 1100, 'is_add_wecom_first_time');
INSERT INTO `t_attribute_location_vip` VALUES (187, 'parseSysUserTemplate', 'where_1', 1103, 'fans_register_time');
INSERT INTO `t_attribute_location_vip` VALUES (188, 'parseSysUserTemplate', 'where_1', 1105, 'fans_register_time');
INSERT INTO `t_attribute_location_vip` VALUES (189, 'parseSysUserTemplate', 'where_1', 1107, 'fans_register_time');
INSERT INTO `t_attribute_location_vip` VALUES (190, 'parseSysUserTemplate', 'where_1', 1110, 'fans_add_wecom_first_time');
INSERT INTO `t_attribute_location_vip` VALUES (191, 'parseSysUserTemplate', 'where_1', 1112, 'fans_add_wecom_first_time');
INSERT INTO `t_attribute_location_vip` VALUES (192, 'parseSysUserTemplate', 'where_1', 1114, 'fans_add_wecom_first_time');
INSERT INTO `t_attribute_location_vip` VALUES (193, 'parseSysUserTemplate', 'havingmin_1|wherenotnull_1', 1117, 'fisrt_pay_time');
INSERT INTO `t_attribute_location_vip` VALUES (194, 'parseSysUserTemplate', 'havingmin_1|wherenotnull_1', 1119, 'fisrt_pay_time');
INSERT INTO `t_attribute_location_vip` VALUES (195, 'parseSysUserTemplate', 'havingmin_1|wherenotnull_1', 1121, 'fisrt_pay_time');
INSERT INTO `t_attribute_location_vip` VALUES (196, 'parseSysUserTemplate', 'havingmax_1|wherenotnull_1', 1124, 'last_pay_time');
INSERT INTO `t_attribute_location_vip` VALUES (197, 'parseSysUserTemplate', 'havingmax_1|wherenotnull_1', 1126, 'last_pay_time');
INSERT INTO `t_attribute_location_vip` VALUES (198, 'parseSysUserTemplate', 'havingmax_1|wherenotnull_1', 1128, 'last_pay_time');
INSERT INTO `t_attribute_location_vip` VALUES (199, 'parseSysUserTemplate', 'where_1', 1131, 'last_pv_time');
INSERT INTO `t_attribute_location_vip` VALUES (200, 'parseSysUserTemplate', 'where_1', 1133, 'last_pv_time');
INSERT INTO `t_attribute_location_vip` VALUES (201, 'parseSysUserTemplate', 'where_1', 1135, 'last_pv_time');
INSERT INTO `t_attribute_location_vip` VALUES (202, 'parseSysUserTemplate', 'where_1', 1138, 'rgst_time');
INSERT INTO `t_attribute_location_vip` VALUES (203, 'parseSysUserTemplate', 'where_1', 1140, 'rgst_time');
INSERT INTO `t_attribute_location_vip` VALUES (204, 'parseSysUserTemplate', 'where_1', 1142, 'rgst_time');
INSERT INTO `t_attribute_location_vip` VALUES (205, 'parseSysUserTemplate', 'where_1', 1108, 'fans_is_wecom_friend = \'true\'');
INSERT INTO `t_attribute_location_vip` VALUES (206, 'parseSysUserTemplate', 'where_1', 1092, 'is_wecom_friend = \'true\'');
INSERT INTO `t_attribute_location_vip` VALUES (207, 'parseNotDoTemplate', 'where_1', 1143, 'dt');
INSERT INTO `t_attribute_location_vip` VALUES (208, 'parseDoTemplate', 'where_1', 1143, 'dt');
INSERT INTO `t_attribute_location_vip` VALUES (209, 'parseDoAndTemplate', 'where_1', 1143, 'dt');
INSERT INTO `t_attribute_location_vip` VALUES (210, 'parseNotDoPayTemplate', 'where_1', 1143, 'dt');
INSERT INTO `t_attribute_location_vip` VALUES (211, 'parseEventDoAndTemplate', 'where_1', 1144, 'dt');
INSERT INTO `t_attribute_location_vip` VALUES (212, 'parseDoTemplate', 'where_3', 1146, 'page_tag');
INSERT INTO `t_attribute_location_vip` VALUES (213, 'parseDoTemplate', 'where_3', 1147, 'activity_type');
INSERT INTO `t_attribute_location_vip` VALUES (214, 'parseDoTemplate', 'where_3', 1148, 'utm_source');
INSERT INTO `t_attribute_location_vip` VALUES (215, 'parseDoTemplate', 'where_3', 1149, 'utm_medium');
INSERT INTO `t_attribute_location_vip` VALUES (216, 'parseDoTemplate', 'where_3', 1150, 'utm_term');
INSERT INTO `t_attribute_location_vip` VALUES (217, 'parseDoTemplate', 'where_3', 1151, 'utm_content');
INSERT INTO `t_attribute_location_vip` VALUES (218, 'parseDoTemplate', 'where_3', 1152, 'url');
INSERT INTO `t_attribute_location_vip` VALUES (219, 'parseDoAndTemplate', 'where_3', 1146, 'page_tag');
INSERT INTO `t_attribute_location_vip` VALUES (220, 'parseDoAndTemplate', 'where_3', 1147, 'activity_type');
INSERT INTO `t_attribute_location_vip` VALUES (221, 'parseDoAndTemplate', 'where_3', 1148, 'utm_source');
INSERT INTO `t_attribute_location_vip` VALUES (222, 'parseDoAndTemplate', 'where_3', 1149, 'utm_medium');
INSERT INTO `t_attribute_location_vip` VALUES (223, 'parseDoAndTemplate', 'where_3', 1150, 'utm_term');
INSERT INTO `t_attribute_location_vip` VALUES (224, 'parseDoAndTemplate', 'where_3', 1151, 'utm_content');
INSERT INTO `t_attribute_location_vip` VALUES (225, 'parseDoAndTemplate', 'where_3', 1152, 'url');
INSERT INTO `t_attribute_location_vip` VALUES (226, 'parseEventDoAndTemplate', 'where_4', 1154, 'page_tag');
INSERT INTO `t_attribute_location_vip` VALUES (227, 'parseEventDoAndTemplate', 'where_4', 1155, 'activity_type');
INSERT INTO `t_attribute_location_vip` VALUES (228, 'parseEventDoAndTemplate', 'where_4', 1156, 'utm_source');
INSERT INTO `t_attribute_location_vip` VALUES (229, 'parseEventDoAndTemplate', 'where_4', 1157, 'utm_medium');
INSERT INTO `t_attribute_location_vip` VALUES (230, 'parseEventDoAndTemplate', 'where_4', 1158, 'utm_term');
INSERT INTO `t_attribute_location_vip` VALUES (231, 'parseEventDoAndTemplate', 'where_4', 1159, 'utm_content');
INSERT INTO `t_attribute_location_vip` VALUES (232, 'parseEventDoAndTemplate', 'where_4', 1160, 'url');
INSERT INTO `t_attribute_location_vip` VALUES (233, 'parseDoTemplate', 'where_3', 1161, 'utm_campaign');
INSERT INTO `t_attribute_location_vip` VALUES (234, 'parseDoAndTemplate', 'where_3', 1161, 'utm_campaign');
INSERT INTO `t_attribute_location_vip` VALUES (235, 'parseEventDoAndTemplate', 'where_4', 1162, 'utm_campaign');
INSERT INTO `t_attribute_location_vip` VALUES (236, 'parseSysUserTemplate', 'where_1', 1163, 'brand_id');
INSERT INTO `t_attribute_location_vip` VALUES (237, 'parseSysUserTemplate', 'where_1', 1170, 'is_add_wecom_first_time');
INSERT INTO `t_attribute_location_vip` VALUES (238, 'parseSysUserTemplate', 'where_1', 1164, 'is_wecom_friend = \'true\'');
INSERT INTO `t_attribute_location_vip` VALUES (239, 'parseSysUserTemplate', 'where_1', 1171, 'brand_id');
INSERT INTO `t_attribute_location_vip` VALUES (240, 'parseSysUserTemplate', 'where_1', 1172, 'is_wecom_friend');
INSERT INTO `t_attribute_location_vip` VALUES (242, 'parseSysUserTemplate', 'where_1', 1175, 'brand_id');
INSERT INTO `t_attribute_location_vip` VALUES (243, 'parseSysUserTemplate', 'where_1', 1176, 'is_wecom_user');
INSERT INTO `t_attribute_location_vip` VALUES (245, 'parseSysUserTemplate', 'where_1', 1179, 'brand_id');
INSERT INTO `t_attribute_location_vip` VALUES (246, 'parseSysUserTemplate', 'where_1', 1180, 'is_sigo_web_register');
INSERT INTO `t_attribute_location_vip` VALUES (248, 'parseSysUserTemplate', 'where_1', 1183, 'brand_id');
INSERT INTO `t_attribute_location_vip` VALUES (249, 'parseSysUserTemplate', 'where_1', 1186, 'sigo_web_register_time');
INSERT INTO `t_attribute_location_vip` VALUES (250, 'parseSysUserTemplate', 'where_1', 1188, 'sigo_web_register_time');
INSERT INTO `t_attribute_location_vip` VALUES (251, 'parseSysUserTemplate', 'where_1', 1190, 'sigo_web_register_time');
INSERT INTO `t_attribute_location_vip` VALUES (253, 'parseSysUserTemplate', 'where_1', 1168, 'is_add_wecom_first_time');
INSERT INTO `t_attribute_location_vip` VALUES (254, 'parseSysUserTemplate', 'where_1', 1166, 'is_add_wecom_first_time');
INSERT INTO `t_attribute_location_vip` VALUES (255, 'parseDoAndTemplate', 'select_1|where_1|group_1|having_1|select_2', 1192, 'degree');
INSERT INTO `t_attribute_location_vip` VALUES (256, 'parseSysUserTemplate', 'partOfArrayJudge_1', 1193, 'degree');
INSERT INTO `t_attribute_location_vip` VALUES (257, 'parseSysUserTemplate', 'partOfArray_1', 1196, '');
INSERT INTO `t_attribute_location_vip` VALUES (258, 'parseEventDoAndTemplate', 'select_1|where_3|group_1|having_1|select_2', 1198, 'degree');
INSERT INTO `t_attribute_location_vip` VALUES (259, 'parseNotDoTemplate', 'where_1', 1002, 'sale_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (260, 'parseDoTemplate', 'where_1', 1002, 'sale_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (261, 'parseDoAndTemplate', 'where_1', 1002, 'sale_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (262, 'parseSysUserTemplate', 'where_1', 1002, 'sale_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (263, 'parseEventDoAndTemplate', 'where_1', 1002, 'sale_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (264, 'parseNotDoPayTemplate', 'where_1', 1002, 'sale_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (265, 'parseAggMaxSceneTemplate', 'where_1', 1002, 'sale_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (266, 'vipParseDoAndTemplate', 'where_1', 10000, 'prmry_busi_mdl_cd');
INSERT INTO `t_attribute_location_vip` VALUES (267, 'vipParseDoAndTemplate', 'where_1', 10001, 'dt');
INSERT INTO `t_attribute_location_vip` VALUES (268, 'vipParseDoAndTemplate', 'selectsum_1|where_2', 10029, 'pv_qty');
INSERT INTO `t_attribute_location_vip` VALUES (269, 'vipParseDoAndTemplate', 'selectsum_1|where_2', 10030, 'pv_day_qty');
INSERT INTO `t_attribute_location_vip` VALUES (270, 'vipParseDoAndTemplate', 'selectsum_1|where_2', 10031, 'spt_qty');
INSERT INTO `t_attribute_location_vip` VALUES (271, 'vipParseDoAndTemplate', 'selectsum_1|where_2', 10032, 'spt_egds_qty');
INSERT INTO `t_attribute_location_vip` VALUES (272, 'vipParseDoAndTemplate', 'selectsum_1|where_2', 10033, 'clt_egds_qty');
INSERT INTO `t_attribute_location_vip` VALUES (273, 'vipParseDoAndTemplate', 'rborcardinality_1|where_2', 10034, 'erp_order_code_rbm');
INSERT INTO `t_attribute_location_vip` VALUES (274, 'vipParseDoAndTemplate', 'selectsum_1|where_2', 10035, 'pay_egds_qty');
INSERT INTO `t_attribute_location_vip` VALUES (275, 'vipParseDoAndTemplate', 'selectsum_1|where_2', 10036, 'pay_ord_amt');
INSERT INTO `t_attribute_location_vip` VALUES (276, 'vipParseDoAndTemplate', 'selectsum_1|where_2', 10037, 'pay_ord_amt/erp_order_code_rbm');
INSERT INTO `t_attribute_location_vip` VALUES (277, 'vipParseDoAndTemplate', 'selectsum_1|where_2', 10038, 'pd_pv_qty');
INSERT INTO `t_attribute_location_vip` VALUES (278, 'vipParseDoAndTemplate', 'select_1|where_1|group_1|having_1|select_2', 10041, 'erp_gds_cd');
INSERT INTO `t_attribute_location_vip` VALUES (279, 'vipParseDoAndTemplate', 'select_1|where_1|group_1|having_1|select_2', 10042, 'erp_brand_id');
INSERT INTO `t_attribute_location_vip` VALUES (280, 'vipParseDoAndTemplate', 'select_1|where_1|group_1|having_1|select_2', 10043, 'dpa_cyc');
INSERT INTO `t_attribute_location_vip` VALUES (281, 'vipParseDoAndTemplate', 'where_1', 10044, 'dpa_cyc');
INSERT INTO `t_attribute_location_vip` VALUES (282, 'vipParseDoAndTemplate', 'where_1', 10045, 'dpa_cyc');
INSERT INTO `t_attribute_location_vip` VALUES (283, 'vipParseDoAndTemplate', 'where_1', 10046, 'dpa_cyc');
INSERT INTO `t_attribute_location_vip` VALUES (284, 'vipParseDoAndTemplate', 'where_1', 10047, 'dpa_cyc');
INSERT INTO `t_attribute_location_vip` VALUES (285, 'vipParseDoAndTemplate', 'where_1', 10048, 'dpa_cyc');
INSERT INTO `t_attribute_location_vip` VALUES (286, 'vipParseDoAndTemplate', 'where_1', 10049, 'dpa_cyc');
INSERT INTO `t_attribute_location_vip` VALUES (287, 'vipParseDoAndTemplate', 'where_1', 10050, 'dpa_cyc');
INSERT INTO `t_attribute_location_vip` VALUES (288, 'vipParseDoAndTemplate', 'where_1', 10051, 'dpa_cyc');
INSERT INTO `t_attribute_location_vip` VALUES (289, 'vipParseDoAndTemplate', 'where_1', 10053, 'is_color');
INSERT INTO `t_attribute_location_vip` VALUES (290, 'vipParseDoAndTemplate', 'where_1', 10054, 'is_color');
INSERT INTO `t_attribute_location_vip` VALUES (291, 'vipParseDoAndTemplate', 'where_1', 10055, 'fisrt_pay_time');
INSERT INTO `t_attribute_location_vip` VALUES (292, 'vipParseDoAndTemplate', 'where_1', 10056, 'last_pay_time');
INSERT INTO `t_attribute_location_vip` VALUES (293, 'vipParseDoAndTemplate', 'where_1', 10057, 'scnd_cate_id');
INSERT INTO `t_attribute_location_vip` VALUES (294, 'vipParseDoAndTemplate', 'where_1', 10058, 'scnd_cate_id');
INSERT INTO `t_attribute_location_vip` VALUES (295, 'vipParseDoAndTemplate', 'where_1', 10059, 'scnd_cate_id');
INSERT INTO `t_attribute_location_vip` VALUES (296, 'vipParseDoAndTemplate', 'where_1', 10060, 'scnd_cate_id');
INSERT INTO `t_attribute_location_vip` VALUES (297, 'vipParseDoAndTemplate', 'where_1', 10061, 'dt');
INSERT INTO `t_attribute_location_vip` VALUES (298, 'vipParseDoAndTemplate', 'where_3', 10063, 'page_tag');
INSERT INTO `t_attribute_location_vip` VALUES (299, 'vipParseDoAndTemplate', 'where_3', 10064, 'activity_type');
INSERT INTO `t_attribute_location_vip` VALUES (300, 'vipParseDoAndTemplate', 'where_3', 10065, 'utm_source');
INSERT INTO `t_attribute_location_vip` VALUES (301, 'vipParseDoAndTemplate', 'where_3', 10066, 'utm_medium');
INSERT INTO `t_attribute_location_vip` VALUES (302, 'vipParseDoAndTemplate', 'where_3', 10067, 'utm_term');
INSERT INTO `t_attribute_location_vip` VALUES (303, 'vipParseDoAndTemplate', 'where_3', 10068, 'utm_content');
INSERT INTO `t_attribute_location_vip` VALUES (304, 'vipParseDoAndTemplate', 'where_3', 10069, 'url');
INSERT INTO `t_attribute_location_vip` VALUES (305, 'vipParseDoAndTemplate', 'where_3', 10070, 'utm_campaign');
INSERT INTO `t_attribute_location_vip` VALUES (306, 'vipParseDoAndTemplate', 'select_1|where_1|group_1|having_1|select_2', 10072, 'degree');
INSERT INTO `t_attribute_location_vip` VALUES (307, 'vipParseDoTemplate', 'where_1', 10000, 'prmry_busi_mdl_cd');
INSERT INTO `t_attribute_location_vip` VALUES (308, 'vipParseDoTemplate', 'where_1', 10001, 'dt');
INSERT INTO `t_attribute_location_vip` VALUES (309, 'vipParseDoTemplate', 'selectsum_1|where_2', 10024, 'pv_qty');
INSERT INTO `t_attribute_location_vip` VALUES (310, 'vipParseDoTemplate', 'selectsum_1|where_2', 10025, 'spt_qty');
INSERT INTO `t_attribute_location_vip` VALUES (311, 'vipParseDoTemplate', 'selectsum_1|where_2', 10026, 'clt_egds_qty');
INSERT INTO `t_attribute_location_vip` VALUES (312, 'vipParseDoTemplate', 'selectsum_1|where_2', 10027, 'pay_ord_qty');
INSERT INTO `t_attribute_location_vip` VALUES (313, 'vipParseDoTemplate', 'selectsum_1|where_2', 10028, 'pd_pv_qty');
INSERT INTO `t_attribute_location_vip` VALUES (314, 'vipParseDoTemplate', 'selectsum_1|where_2', 10029, 'pv_qty');
INSERT INTO `t_attribute_location_vip` VALUES (315, 'vipParseDoTemplate', 'selectsum_1|where_2', 10030, 'pv_day_qty');
INSERT INTO `t_attribute_location_vip` VALUES (316, 'vipParseDoTemplate', 'selectsum_1|where_2', 10031, 'spt_qty');
INSERT INTO `t_attribute_location_vip` VALUES (317, 'vipParseDoTemplate', 'selectsum_1|where_2', 10032, 'spt_egds_qty');
INSERT INTO `t_attribute_location_vip` VALUES (318, 'vipParseDoTemplate', 'selectsum_1|where_2', 10033, 'clt_egds_qty');
INSERT INTO `t_attribute_location_vip` VALUES (319, 'vipParseDoTemplate', 'selectsum_1|where_2', 10034, 'pay_ord_qty');
INSERT INTO `t_attribute_location_vip` VALUES (320, 'vipParseDoTemplate', 'selectsum_1|where_2', 10035, 'pay_egds_qty');
INSERT INTO `t_attribute_location_vip` VALUES (321, 'vipParseDoTemplate', 'selectsum_1|where_2', 10036, 'pay_ord_amt');
INSERT INTO `t_attribute_location_vip` VALUES (322, 'vipParseDoTemplate', 'selectsum_1|where_2', 10037, 'pay_ord_amt/pay_ord_qty');
INSERT INTO `t_attribute_location_vip` VALUES (323, 'vipParseDoTemplate', 'selectsum_1|where_2', 10038, 'pd_pv_qty');
INSERT INTO `t_attribute_location_vip` VALUES (324, 'vipParseDoTemplate', 'where_1', 10055, 'fisrt_pay_time');
INSERT INTO `t_attribute_location_vip` VALUES (325, 'vipParseDoTemplate', 'where_1', 10056, 'last_pay_time');
INSERT INTO `t_attribute_location_vip` VALUES (326, 'vipParseDoTemplate', 'where_1', 10061, 'dt');
INSERT INTO `t_attribute_location_vip` VALUES (327, 'vipParseDoTemplate', 'where_3', 10063, 'page_tag');
INSERT INTO `t_attribute_location_vip` VALUES (328, 'vipParseDoTemplate', 'where_3', 10064, 'activity_type');
INSERT INTO `t_attribute_location_vip` VALUES (329, 'vipParseDoTemplate', 'where_3', 10065, 'utm_source');
INSERT INTO `t_attribute_location_vip` VALUES (330, 'vipParseDoTemplate', 'where_3', 10066, 'utm_medium');
INSERT INTO `t_attribute_location_vip` VALUES (331, 'vipParseDoTemplate', 'where_3', 10067, 'utm_term');
INSERT INTO `t_attribute_location_vip` VALUES (332, 'vipParseDoTemplate', 'where_3', 10068, 'utm_content');
INSERT INTO `t_attribute_location_vip` VALUES (333, 'vipParseDoTemplate', 'where_3', 10069, 'url');
INSERT INTO `t_attribute_location_vip` VALUES (334, 'vipParseDoTemplate', 'where_3', 10070, 'utm_campaign');
INSERT INTO `t_attribute_location_vip` VALUES (335, 'vipParseNotDoPayTemplate', 'where_3|on_1|where_1|where_4', 10000, 'prmry_busi_mdl_cd');
INSERT INTO `t_attribute_location_vip` VALUES (336, 'vipParseNotDoPayTemplate', 'where_1', 10001, 'dt');
INSERT INTO `t_attribute_location_vip` VALUES (337, 'vipParseNotDoPayTemplate', 'where_1', 10061, 'dt');
INSERT INTO `t_attribute_location_vip` VALUES (338, 'vipParseNotDoTemplate', 'where_3|on_1', 10000, 'prmry_busi_mdl_cd');
INSERT INTO `t_attribute_location_vip` VALUES (339, 'vipParseNotDoTemplate', 'where_1', 10001, 'dt');
INSERT INTO `t_attribute_location_vip` VALUES (340, 'vipParseNotDoTemplate', 'where_2', 10024, 'pv_qty');
INSERT INTO `t_attribute_location_vip` VALUES (341, 'vipParseNotDoTemplate', 'where_2', 10025, 'spt_qty');
INSERT INTO `t_attribute_location_vip` VALUES (342, 'vipParseNotDoTemplate', 'where_2', 10026, 'clt_egds_qty');
INSERT INTO `t_attribute_location_vip` VALUES (343, 'vipParseNotDoTemplate', 'where_2', 10027, 'pay_ord_qty');
INSERT INTO `t_attribute_location_vip` VALUES (344, 'vipParseNotDoTemplate', 'where_2', 10028, 'pd_pv_qty');
INSERT INTO `t_attribute_location_vip` VALUES (345, 'vipParseNotDoTemplate', 'where_1', 10061, 'dt');
INSERT INTO `t_attribute_location_vip` VALUES (346, 'parseSysUserTemplate', 'where_1', 11002, 'rgst_time');
INSERT INTO `t_attribute_location_vip` VALUES (347, 'parseSysUserTemplate', 'where_1', 11004, 'rgst_time');
INSERT INTO `t_attribute_location_vip` VALUES (348, 'parseSysUserTemplate', 'where_1', 11006, 'rgst_time');
INSERT INTO `t_attribute_location_vip` VALUES (349, 'vipParseAggMaxSceneTemplate', 'where_1', 1002, 'sale_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (350, 'vipParseAggMaxSceneTemplate', 'where_1', 1000, 'prmry_busi_mdl_cd');
INSERT INTO `t_attribute_location_vip` VALUES (351, 'vipParseAggMaxSceneTemplate', 'where_1', 1001, 'chnl_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (352, 'vipParseDoAndTemplate', 'where_1', 1002, 'sale_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (353, 'vipParseDoAndTemplate', 'where_1', 1000, 'prmry_busi_mdl_cd');
INSERT INTO `t_attribute_location_vip` VALUES (354, 'vipParseDoAndTemplate', 'where_1', 1001, 'chnl_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (355, 'vipParseDoTemplate', 'where_1', 1002, 'sale_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (356, 'vipParseDoTemplate', 'where_1', 1000, 'prmry_busi_mdl_cd');
INSERT INTO `t_attribute_location_vip` VALUES (357, 'vipParseDoTemplate', 'where_1', 1001, 'chnl_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (358, 'vipParseEventDoAndTemplate', 'select_1|where_3|group_1|having_1|select_2', 1198, 'degree');
INSERT INTO `t_attribute_location_vip` VALUES (359, 'vipParseEventDoAndTemplate', 'where_1', 1002, 'sale_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (360, 'vipParseEventDoAndTemplate', 'select_1|where_3|group_1|having_1|select_2', 147, 'erp_gds_cd');
INSERT INTO `t_attribute_location_vip` VALUES (361, 'vipParseEventDoAndTemplate', 'select_1|where_3|group_1|having_1|select_2', 148, 'erp_brand_id');
INSERT INTO `t_attribute_location_vip` VALUES (362, 'vipParseEventDoAndTemplate', 'select_1|where_3|group_1|having_1|select_2', 150, 'dpa_cyc');
INSERT INTO `t_attribute_location_vip` VALUES (363, 'vipParseEventDoAndTemplate', 'select_1|where_3|group_1|having_1|select_2', 152, 'scnd_cate_id');
INSERT INTO `t_attribute_location_vip` VALUES (364, 'vipParseEventDoAndTemplate', 'selectsum_1|where_2', 130, 'pv_qty');
INSERT INTO `t_attribute_location_vip` VALUES (365, 'vipParseEventDoAndTemplate', 'selectsum_1|where_2', 131, 'pv_day_qty');
INSERT INTO `t_attribute_location_vip` VALUES (366, 'vipParseEventDoAndTemplate', 'selectsum_1|where_2', 132, 'spt_qty');
INSERT INTO `t_attribute_location_vip` VALUES (367, 'vipParseEventDoAndTemplate', 'selectsum_1|where_2', 133, 'spt_egds_qty');
INSERT INTO `t_attribute_location_vip` VALUES (368, 'vipParseEventDoAndTemplate', 'selectsum_1|where_2', 134, 'clt_egds_qty');
INSERT INTO `t_attribute_location_vip` VALUES (369, 'vipParseEventDoAndTemplate', 'rborcardinality_1|where_2', 135, 'erp_order_code_rbm');
INSERT INTO `t_attribute_location_vip` VALUES (370, 'vipParseEventDoAndTemplate', 'selectsum_1|where_2', 136, 'pay_egds_qty');
INSERT INTO `t_attribute_location_vip` VALUES (371, 'vipParseEventDoAndTemplate', 'selectsum_1|where_2', 137, 'pay_ord_amt');
INSERT INTO `t_attribute_location_vip` VALUES (372, 'vipParseEventDoAndTemplate', 'selectsum_1|where_2', 138, 'pay_ord_amt/erp_order_code_rbm');
INSERT INTO `t_attribute_location_vip` VALUES (373, 'vipParseEventDoAndTemplate', 'selectsum_1|where_2', 139, 'pd_pv_qty');
INSERT INTO `t_attribute_location_vip` VALUES (374, 'vipParseEventDoAndTemplate', 'where_1', 118, 'prmry_busi_mdl_cd');
INSERT INTO `t_attribute_location_vip` VALUES (375, 'vipParseEventDoAndTemplate', 'where_1', 119, 'dt');
INSERT INTO `t_attribute_location_vip` VALUES (376, 'vipParseEventDoAndTemplate', 'where_1', 1000, 'prmry_busi_mdl_cd');
INSERT INTO `t_attribute_location_vip` VALUES (377, 'vipParseEventDoAndTemplate', 'where_1', 1001, 'chnl_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (378, 'vipParseEventDoAndTemplate', 'where_1', 452, 'fisrt_pay_time');
INSERT INTO `t_attribute_location_vip` VALUES (379, 'vipParseEventDoAndTemplate', 'where_1', 453, 'last_pay_time');
INSERT INTO `t_attribute_location_vip` VALUES (380, 'vipParseEventDoAndTemplate', 'where_1', 1144, 'dt');
INSERT INTO `t_attribute_location_vip` VALUES (381, 'vipParseEventDoAndTemplate', 'where_4', 1155, 'activity_type');
INSERT INTO `t_attribute_location_vip` VALUES (382, 'vipParseEventDoAndTemplate', 'where_4', 1156, 'utm_source');
INSERT INTO `t_attribute_location_vip` VALUES (383, 'vipParseEventDoAndTemplate', 'where_4', 1157, 'utm_medium');
INSERT INTO `t_attribute_location_vip` VALUES (384, 'vipParseEventDoAndTemplate', 'where_4', 1158, 'utm_term');
INSERT INTO `t_attribute_location_vip` VALUES (385, 'vipParseEventDoAndTemplate', 'where_4', 1159, 'utm_content');
INSERT INTO `t_attribute_location_vip` VALUES (386, 'vipParseEventDoAndTemplate', 'where_4', 1160, 'url');
INSERT INTO `t_attribute_location_vip` VALUES (387, 'vipParseEventDoAndTemplate', 'where_4', 1162, 'utm_campaign');
INSERT INTO `t_attribute_location_vip` VALUES (388, 'vipParseNotDoPayTemplate', 'where_1', 1002, 'sale_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (389, 'vipParseNotDoPayTemplate', 'where_1', 1000, 'prmry_busi_mdl_cd');
INSERT INTO `t_attribute_location_vip` VALUES (390, 'vipParseNotDoPayTemplate', 'where_1', 1001, 'chnl_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (391, 'vipParseNotDoTemplate', 'where_1', 1002, 'sale_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (392, 'vipParseNotDoTemplate', 'where_1', 1000, 'prmry_busi_mdl_cd');
INSERT INTO `t_attribute_location_vip` VALUES (393, 'vipParseNotDoTemplate', 'where_1', 1001, 'chnl_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (394, 'vipParseSysUserTemplate', 'where_1', 1002, 'sale_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (395, 'vipParseSysUserTemplate', 'where_1', 1000, 'prmry_busi_mdl_cd');
INSERT INTO `t_attribute_location_vip` VALUES (396, 'vipParseSysUserTemplate', 'where_1', 1001, 'chnl_str_cd');
INSERT INTO `t_attribute_location_vip` VALUES (397, 'vipParseDoCouponPrizeTemplate', 'where_1', 10000, 'chnl_tp_cd');
INSERT INTO `t_attribute_location_vip` VALUES (398, 'vipParseDoCouponPrizeTemplate', 'where_1', 10001, 'dt');
INSERT INTO `t_attribute_location_vip` VALUES (399, 'vipParseDoCouponPrizeTemplate', 'selectsum_1|where_2', 10004, 'get_coupon');
INSERT INTO `t_attribute_location_vip` VALUES (400, 'vipParseDoCouponPrizeTemplate', 'selectsum_1|where_2', 10005, 'use_coupon');
INSERT INTO `t_attribute_location_vip` VALUES (401, 'vipParseDoCouponPrizeTemplate', 'selectsum_1|where_2', 10006, 'win_prize');
INSERT INTO `t_attribute_location_vip` VALUES (402, 'vipParseDoCouponPrizeTemplate', 'selectsum_1|where_2', 10007, 'claim_prize');
INSERT INTO `t_attribute_location_vip` VALUES (403, 'vipParseDoAndCouponPrizeTemplate', 'select_1|where_1|group_1|having_1|select_2', 10017, 'product_code');
INSERT INTO `t_attribute_location_vip` VALUES (404, 'vipParseDoAndCouponPrizeTemplate', 'select_1|where_1|group_1|having_1|select_2', 10018, 'template_id');
INSERT INTO `t_attribute_location_vip` VALUES (405, 'vipParseNotDoCouponPrizeTemplate', 'where_3|on_1', 10000, 'chnl_tp_cd');
INSERT INTO `t_attribute_location_vip` VALUES (406, 'vipParseNotDoCouponPrizeTemplate', 'where_1', 10001, 'dt');
INSERT INTO `t_attribute_location_vip` VALUES (407, 'vipParseNotDoCouponPrizeTemplate', 'where_2', 10021, 'is_valid');
INSERT I